spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/module
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null

mybatis:
  type-aliases-package: com.module.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 80


