spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/module
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.module.entity
server:
  port: 80
